# Generated by Django 3.2.5 on 2021-08-01 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trivia', '0002_auto_20210801_0140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
